global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - alertname
  - rc_edgeid
  - service
  source_match:
    severity: critical
  target_match:
    severity: warning
receivers:
- name: default-receiver
- name: rafay-webhook
  webhook_configs:
  - http_config:
      tls_config:
        ca_file: /etc/config/certs/ca.crt
        cert_file: /etc/config/certs/client.crt
        insecure_skip_verify: true
        key_file: /etc/config/certs/client.key
        server_name: '{{{ .V2EventFrameworkFQDN }}}'
    url: https://{{{ .V2EventFrameworkFQDN }}}/event/v1/alert/raise
- name: sns
  sns_configs:
    - sigv4:
        region: us-west-2
    topic_arn: arn:aws:sns:us-west-2:679196758854:MyTopic_SNS_Alerts
    subject: SNS_Alerts
    attributes:
       key: severity
       value: SEV2
route:
  group_interval: 5m
  group_wait: 10s
  receiver: rafay-webhook
  repeat_interval: 3h
  routes:
  - continue: true
    match_re:
      severity: .*
    receiver: sns
